<a href="https://colab.research.google.com/github/MahrabaMarjan/Datascience/blob/main/dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DataFrame #two dimensional

In [ ]:
import pandas as pd
import numpy as np
data={
   "Name":["Alice","Bob","Charlie","David","Emma"],
   "Age":[20,21,19,22,20],
   "Marks":[85,72,np.nan,90,65],
   "Attendance":[95,80,75,np.nan,88],
   "City":["Kochi","Delhi","Mumbai","Kochi","Chennai"]
}
df=pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
      Name  Age  Marks  Attendance     City
0    Alice   20   85.0        95.0    Kochi
1      Bob   21   72.0        80.0    Delhi
2  Charlie   19    NaN        75.0   Mumbai
3    David   22   90.0         NaN    Kochi
4     Emma   20   65.0        88.0  Chennai

In [ ]:
print(df.head(3))

      Name  Age  Marks  Attendance    City
0    Alice   20   85.0        95.0   Kochi
1      Bob   21   72.0        80.0   Delhi
2  Charlie   19    NaN        75.0  Mumbai

In [ ]:
print(df.tail(2))

    Name  Age  Marks  Attendance     City
3  David   22   90.0         NaN    Kochi
4   Emma   20   65.0        88.0  Chennai

In [ ]:
print(df.shape)
print(df.columns)

(5, 5)
Index(['Name', 'Age', 'Marks', 'Attendance', 'City'], dtype='object')

In [ ]:
print(df.dtypes)                       #for datatypes

Name           object
Age             int64
Marks         float64
Attendance    float64
City           object
dtype: object

In [ ]:
print(df["Marks"])

0    85.0
1    72.0
2     NaN
3    90.0
4    65.0
Name: Marks, dtype: float64

In [ ]:
print(df.iloc[0:3])

      Name  Age  Marks  Attendance    City
0    Alice   20   85.0        95.0   Kochi
1      Bob   21   72.0        80.0   Delhi
2  Charlie   19    NaN        75.0  Mumbai

In [ ]:
print(df.iloc[1:5])

      Name  Age  Marks  Attendance     City
1      Bob   21   72.0        80.0    Delhi
2  Charlie   19    NaN        75.0   Mumbai
3    David   22   90.0         NaN    Kochi
4     Emma   20   65.0        88.0  Chennai

In [ ]:
print(df.loc[0:3,["Name","Marks"]])

      Name  Marks
0    Alice   85.0
1      Bob   72.0
2  Charlie    NaN
3    David   90.0

In [ ]:
print(df[df["Marks"] > 75])

    Name  Age  Marks  Attendance   City
0  Alice   20   85.0        95.0  Kochi
3  David   22   90.0         NaN  Kochi

In [ ]:
print(df[df["Marks"] < 75])

   Name  Age  Marks  Attendance     City
1   Bob   21   72.0        80.0    Delhi
4  Emma   20   65.0        88.0  Chennai

In [ ]:
print(df[df["Marks"] == 72])

  Name  Age  Marks  Attendance   City
1  Bob   21   72.0        80.0  Delhi

In [ ]:
print(df[df["Marks"] == 75])

Empty DataFrame
Columns: [Name, Age, Marks, Attendance, City]
Index: []

In [ ]:
print(df[df["City"] == "Kochi"])

    Name  Age  Marks  Attendance   City
0  Alice   20   85.0        95.0  Kochi
3  David   22   90.0         NaN  Kochi

In [ ]:
print(
    df[
    (df["Marks"] < 75)
           &
    (df["Attendance"] > 50)
    ]
)

   Name  Age  Marks  Attendance     City
1   Bob   21   72.0        80.0    Delhi
4  Emma   20   65.0        88.0  Chennai

In [ ]:
print(df["Marks"].mean())
print(df["Marks"].max())
print(df["Marks"].sum())

78.0
90.0
312.0

In [ ]:
#Methametic operations

In [ ]:
print(df["Marks"]+5)

0    90.0
1    77.0
2     NaN
3    95.0
4    70.0
Name: Marks, dtype: float64

In [ ]:
print(df["Marks"]*5)

0    425.0
1    360.0
2      NaN
3    450.0
4    325.0
Name: Marks, dtype: float64

In [ ]:
print(df.sort_values("Marks"))

      Name  Age  Marks  Attendance     City
4     Emma   20   65.0        88.0  Chennai
1      Bob   21   72.0        80.0    Delhi
0    Alice   20   85.0        95.0    Kochi
3    David   22   90.0         NaN    Kochi
2  Charlie   19    NaN        75.0   Mumbai

In [ ]:
print(df.sort_values("Marks",ascending=False))

      Name  Age  Marks  Attendance     City
3    David   22   90.0         NaN    Kochi
0    Alice   20   85.0        95.0    Kochi
1      Bob   21   72.0        80.0    Delhi
4     Emma   20   65.0        88.0  Chennai
2  Charlie   19    NaN        75.0   Mumbai

In [ ]:
x=df.rename(
    columns={
      "Marks":"score",
      "Attendance":"Hajar"
    }
)
print(x)

      Name  Age  score  Hajar     City
0    Alice   20   85.0   95.0    Kochi
1      Bob   21   72.0   80.0    Delhi
2  Charlie   19    NaN   75.0   Mumbai
3    David   22   90.0    NaN    Kochi
4     Emma   20   65.0   88.0  Chennai

In [ ]:
print(df.isna())

    Name    Age  Marks  Attendance   City
0  False  False  False       False  False
1  False  False  False       False  False
2  False  False   True       False  False
3  False  False  False        True  False
4  False  False  False       False  False

In [ ]:
print(df.isna().sum())

Name          0
Age           0
Marks         1
Attendance    1
City          0
dtype: int64

In [ ]:
print(df.dropna())

    Name  Age  Marks  Attendance     City
0  Alice   20   85.0        95.0    Kochi
1    Bob   21   72.0        80.0    Delhi
4   Emma   20   65.0        88.0  Chennai

In [ ]:
print(df.fillna(30))

      Name  Age  Marks  Attendance     City
0    Alice   20   85.0        95.0    Kochi
1      Bob   21   72.0        80.0    Delhi
2  Charlie   19   30.0        75.0   Mumbai
3    David   22   90.0        30.0    Kochi
4     Emma   20   65.0        88.0  Chennai

In [ ]:
df_forward=df.copy()
df_forward=df_forward.ffill()
print(df_forward)

      Name  Age  Marks  Attendance     City
0    Alice   20   85.0        95.0    Kochi
1      Bob   21   72.0        80.0    Delhi
2  Charlie   19   72.0        75.0   Mumbai
3    David   22   90.0        75.0    Kochi
4     Emma   20   65.0        88.0  Chennai

In [ ]:
df_backward=df.copy()
df_backward=df_backward.bfill()
print(df_backward)

      Name  Age  Marks  Attendance     City
0    Alice   20   85.0        95.0    Kochi
1      Bob   21   72.0        80.0    Delhi
2  Charlie   19   90.0        75.0   Mumbai
3    David   22   90.0        88.0    Kochi
4     Emma   20   65.0        88.0  Chennai

In [74]:
df=pd.read_csv("/content/nigeria_messy_sales_dataset (1).csv")
df

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,NaN,rivers,KEYBOARD,NaN,NaN,NaN,27-04-2025,Online,NaN
1,Allison Hill,Lagos,Headphones,NaN,267992.94,NaN,15-03-2024,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
2,Noah Rhodes,Anambra,Keyboard,NaN,42364.41,NaN,10-12-2024,NaN,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed
3,Angie Henderson,Delta,Keyboard,NaN,279444.94,NaN,05-04-2024,NaN,74503887-48d9-4846-95c5-51fcfba57cc8
4,Daniel Wagner,Delta,Tablet,NaN,95899.74,NaN,12-01-2025,NaN,8639bd41-8b15-4d94-a42d-0cd7fd359f6a
...,...,...,...,...,...,...,...,...,...
545,Zachary Mitchell,Ekiti,Monitor,6.0,23989.09,143934.54,07-07-2025,Wholesale,b9744cde-d259-4960-aee3-560792ea1324
546,NaN,Katsina,Tablet,NaN,223764.24,NaN,11-02-2025,Wholesale,NaN
547,Katherine Martinez,Bauchi,Phone,NaN,104084.92,NaN,18-05-2025,Retail,61fa8e7a-078c-46ce-bf02-23bc651ea252
548,Jodi Roach,Niger,Charger,NaN,29756.89,NaN,29-06-2025,Direct,5a9c0679-2c3d-47e2-ad39-da75aee70ab2
549,Brandon Fleming,imo,Camera,NaN,70027.13,NaN,20-02-2024,NaN,46653497-2fe9-42aa-a886-a01136f7a26c

1. Load the Nigeria sales dataset into a DataFrame named sales_df. Display the dataset and identify the number of records and columns available.
2. The manager wants to review basic information about the sales data. Display the first 7 records and the last 5 records.
3. The sales team wants to focus on the Product, Units Sold, Unit Price, and Total Sale information. Display only these details.
4. Find all sales transactions where the Units Sold is greater than 50. Display the complete records.
5. The manager wants to identify transactions where the Unit Price is greater than 100,000. Display the relevant sales records.
6. Find all transactions made through the Online sales channel.
7. The manager wants to know which different states are present in the dataset. Also determine how many different states are available.
8. Find out how many sales transactions belong to each Sales Channel.
9. The company wants to understand the quality of the dataset. Find the number of missing values present in each column.
10. Prepare a new dataset containing only records with complete information. Then find how many records remain after removing incomplete records.

# 1

In [75]:
df.shape

(550, 9)

# 2

In [76]:
df.head(7)

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,NaN,rivers,KEYBOARD,NaN,NaN,NaN,27-04-2025,Online,NaN
1,Allison Hill,Lagos,Headphones,NaN,267992.94,NaN,15-03-2024,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
2,Noah Rhodes,Anambra,Keyboard,NaN,42364.41,NaN,10-12-2024,NaN,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed
3,Angie Henderson,Delta,Keyboard,NaN,279444.94,NaN,05-04-2024,NaN,74503887-48d9-4846-95c5-51fcfba57cc8
4,Daniel Wagner,Delta,Tablet,NaN,95899.74,NaN,12-01-2025,NaN,8639bd41-8b15-4d94-a42d-0cd7fd359f6a
5,Cristian Santos,Oyo,Camera,NaN,118189.90,NaN,30-08-2023,Direct,225aed6c-f045-4043-a3a6-8a707e710b55
6,Connie Lawrence,Rivers,Tablet,36.0,185141.90,6665108.4,10-09-2024,Wholesale,45d8a6ad-77d0-459e-8114-14f8d9df0d0e

In [77]:
df.tail(5)

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
545,Zachary Mitchell,Ekiti,Monitor,6.0,23989.09,143934.54,07-07-2025,Wholesale,b9744cde-d259-4960-aee3-560792ea1324
546,NaN,Katsina,Tablet,NaN,223764.24,NaN,11-02-2025,Wholesale,NaN
547,Katherine Martinez,Bauchi,Phone,NaN,104084.92,NaN,18-05-2025,Retail,61fa8e7a-078c-46ce-bf02-23bc651ea252
548,Jodi Roach,Niger,Charger,NaN,29756.89,NaN,29-06-2025,Direct,5a9c0679-2c3d-47e2-ad39-da75aee70ab2
549,Brandon Fleming,imo,Camera,NaN,70027.13,NaN,20-02-2024,NaN,46653497-2fe9-42aa-a886-a01136f7a26c

# 3

In [89]:
(df["Product"],["Units Sold"],["Unit Price"],["Total Sale"])

(0        KEYBOARD
 1      Headphones
 2        Keyboard
 3        Keyboard
 4          Tablet
           ...
 545       Monitor
 546        Tablet
 547         Phone
 548       Charger
 549        Camera
 Name: Product, Length: 550, dtype: object,
 ['Units Sold'],
 ['Unit Price'],
 ['Total Sale'])

#4

In [78]:
print(df[df["Units Sold"]>50])

            Customer Name        State     Product  Units Sold  Unit Price  \
19           Derek Zuniga          Imo  Headphones        77.0    92649.51
31          Zachary Hicks      Anambra      Camera        68.0    15880.87
32      Anthony Rodriguez          Oyo     MONITOR        96.0   144394.41
37         Debra Davidson        Benue       Phone        65.0   246587.56
38         Jeffrey Chavez       Rivers     Charger        79.0    73037.87
..                    ...          ...         ...         ...         ...
515       Julie Dominguez  Cross River     Monitor        59.0   270431.25
522         Howard Norman        benue      Camera        69.0    84471.72
528      Samantha Gardner       Rivers  HEADPHONES        52.0    62543.86
541         Phillip Berry       Bauchi  Headphones        97.0   115461.94
544  Mr. Justin Green III       Sokoto    KEYBOARD        65.0   206948.51

      Total Sale   Sale Date Sales Channel  \
19    7134012.27  18-03-2025        Online
31    1079899.16  16-04-2024     Wholesale
32   13861863.36  13-09-2024        Online
37   16028191.40  11-09-2024     Wholesale
38    5769991.73  19-10-2023     Wholesale
..           ...         ...           ...
515  15955443.75  17-02-2024        Retail
522   5828548.68  28-09-2024           NaN
528   3252280.72  07-07-2025           NaN
541  11199808.18  14-05-2024           NaN
544  13451653.15  02-12-2023        Online

                                 Order ID
19   4459bd6e-c0f6-4229-b25d-42593c4b1eec
31   fd247c11-bf6b-4cdf-b479-7b6127372b52
32   b3b26337-6a74-4bb7-9fa5-e0aa9b11b530
37   87365a84-725e-434d-8687-9aa914f573d0
38   ead08c89-13fe-4a29-9c9d-eee0b42a0456
..                                    ...
515  1be5a4c3-95af-4d0c-8528-5425c7a9f33c
522  4de1087b-afa1-4a55-8ebe-abaa28597b34
528  2c82989f-fd9c-4bb0-91f1-6485429a4a7c
541  178be968-20f8-4ba2-8f2e-32967184b713
544  ec93e596-2b01-4723-8cf6-97a57603c36c

[72 rows x 9 columns]

# 5

In [91]:
df[df["Unit Price"]>100000]

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
1,Allison Hill,Lagos,Headphones,NaN,267992.94,NaN,15-03-2024,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
3,Angie Henderson,Delta,Keyboard,NaN,279444.94,NaN,05-04-2024,NaN,74503887-48d9-4846-95c5-51fcfba57cc8
5,Cristian Santos,Oyo,Camera,NaN,118189.90,NaN,30-08-2023,Direct,225aed6c-f045-4043-a3a6-8a707e710b55
6,Connie Lawrence,Rivers,Tablet,36.0,185141.90,6665108.40,10-09-2024,Wholesale,45d8a6ad-77d0-459e-8114-14f8d9df0d0e
7,Abigail Shaffer,Imo,Keyboard,NaN,252859.28,NaN,04-09-2024,Online,54a7b69b-1cd6-4b09-8f0e-6d2b315c167a
...,...,...,...,...,...,...,...,...,...
542,Jennifer Banks,Imo,Monitor,NaN,222053.68,NaN,14-03-2025,Online,cf133b65-d450-4fa2-98e7-0aebe7b33085
543,Brian Fitzgerald,Katsina,Laptop,NaN,237254.18,NaN,29-07-2024,NaN,f1394e3c-0aee-4557-9f5d-f91254e07431
544,Mr. Justin Green III,Sokoto,KEYBOARD,65.0,206948.51,13451653.15,02-12-2023,Online,ec93e596-2b01-4723-8cf6-97a57603c36c
546,NaN,Katsina,Tablet,NaN,223764.24,NaN,11-02-2025,Wholesale,NaN
547,Katherine Martinez,Bauchi,Phone,NaN,104084.92,NaN,18-05-2025,Retail,61fa8e7a-078c-46ce-bf02-23bc651ea252

#6

In [96]:
df[df["Sales Channel"]=="Online"]

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,NaN,rivers,KEYBOARD,NaN,NaN,NaN,27-04-2025,Online,NaN
7,Abigail Shaffer,Imo,Keyboard,NaN,252859.28,NaN,04-09-2024,Online,54a7b69b-1cd6-4b09-8f0e-6d2b315c167a
19,Derek Zuniga,Imo,Headphones,77.0,92649.51,7134012.27,18-03-2025,Online,4459bd6e-c0f6-4229-b25d-42593c4b1eec
23,Patty Perez,Delta,Camera,NaN,188963.51,NaN,13-10-2023,Online,77242041-1e43-4bd2-aaf4-07f70fe76149
24,Ethan Adams,Ekiti,LAPTOP,4.0,179274.43,717097.72,14-12-2023,Online,afa28559-67c9-4204-a8e3-33b64e8adc4b
...,...,...,...,...,...,...,...,...,...
525,Jasmine Beltran,Delta,Tablet,NaN,54216.67,NaN,03-02-2025,Online,b60e695c-1759-4a96-a5f8-8c7453ea4919
534,William Gould,Abuja,Laptop,NaN,90133.43,NaN,26-05-2025,Online,c7ecfe71-d493-47fc-8fc9-8d2e030f9be9
538,Austin Osborne,Ekiti,Keyboard,NaN,203271.97,NaN,24-06-2025,Online,eadc9960-4242-41e2-960b-e0f495132c22
542,Jennifer Banks,Imo,Monitor,NaN,222053.68,NaN,14-03-2025,Online,cf133b65-d450-4fa2-98e7-0aebe7b33085
544,Mr. Justin Green III,Sokoto,KEYBOARD,65.0,206948.51,13451653.15,02-12-2023,Online,ec93e596-2b01-4723-8cf6-97a57603c36c

# 7

In [109]:
df["State"].unique()

array(['rivers', 'Lagos', 'Anambra', 'Delta', 'Oyo', 'Rivers', 'Imo',
       'Kano', 'plateau', 'Niger', 'Abuja', 'Enugu', 'Bauchi', 'Katsina',
       'lagos', 'Ekiti', 'Plateau', 'Kaduna', 'Sokoto', 'kano', 'Benue',
       'Osun', 'imo', 'Borno', 'enugu', 'anambra', 'katsina', 'delta',
       'Cross River', 'oyo', 'osun', 'kaduna', 'niger', 'borno', 'abuja',
       'bauchi', 'cross river', 'ekiti', 'sokoto', 'benue'], dtype=object)

In [110]:
df["State"].nunique()

40

# 8

In [113]:
df["Sales Channel"].value_counts()

Sales Channel
Direct       124
Wholesale    111
Retail       108
Online       101
Name: count, dtype: int64

# 9

In [103]:
df.isna()

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,True,False,False,True,True,True,False,False,True
1,False,False,False,True,False,True,False,False,False
2,False,False,False,True,False,True,False,True,False
3,False,False,False,True,False,True,False,True,False
4,False,False,False,True,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...
545,False,False,False,False,False,False,False,False,False
546,True,False,False,True,False,True,False,False,True
547,False,False,False,True,False,True,False,False,False
548,False,False,False,True,False,True,False,False,False
549,False,False,False,True,False,True,False,True,False

# 10

In [115]:
df.dropna()

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
6,Connie Lawrence,Rivers,Tablet,36.0,185141.90,6665108.40,10-09-2024,Wholesale,45d8a6ad-77d0-459e-8114-14f8d9df0d0e
11,Monica Herrera,Abuja,Laptop,3.0,153159.37,459478.11,02-05-2025,Retail,317304b5-c1dd-484a-aca5-8d95915a1c30
12,Jamie Arnold,Lagos,Tablet,43.0,147209.07,6329990.01,10-11-2023,Wholesale,a383889a-db2c-4ac8-9c67-83932ced3c0d
18,Holly Wood,lagos,Headphones,43.0,125253.81,5385913.83,23-11-2023,Direct,6231ee73-42c2-42eb-81bf-9e733f800385
19,Derek Zuniga,Imo,Headphones,77.0,92649.51,7134012.27,18-03-2025,Online,4459bd6e-c0f6-4229-b25d-42593c4b1eec
...,...,...,...,...,...,...,...,...,...
517,Judith Carter,Kano,Laptop,46.0,170251.85,7831585.10,25-08-2023,Wholesale,1ee89a4c-6811-44e2-9064-7c59774f6354
527,Monica Miller,Lagos,Laptop,47.0,5189.60,243911.20,01-05-2025,Retail,4c80d33a-ad5b-43c8-8c88-0714837217e0
537,Lawrence Harrington,Rivers,Monitor,16.0,254908.01,4078528.16,05-07-2025,Direct,15839b99-a50a-43dc-b004-e897a15b2e18
544,Mr. Justin Green III,Sokoto,KEYBOARD,65.0,206948.51,13451653.15,02-12-2023,Online,ec93e596-2b01-4723-8cf6-97a57603c36c
545,Zachary Mitchell,Ekiti,Monitor,6.0,23989.09,143934.54,07-07-2025,Wholesale,b9744cde-d259-4960-aee3-560792ea1324